apis:
  archipelago-workers@v1:
    root: docs/openapi.yaml
  stats@v1:
    root: docs/stats/openapi.yaml
  ws-connector@v1:
    root: docs/ws-connector/openapi.yaml

extends:
  - recommended

rules:
  security-defined: off
  info-license: off
  operation-4xx-response: warn
  no-unused-components: warn
