name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  archipelago-ea-ws-connector-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-release.yml@main
    with:
      service-name: archipelago-ea-ws-connector
      image-name: archipelago-workers
      deployment-environment: prd
    secrets: inherit
