name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  archipelago-ea-ws-connector-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: archipelago-ea-ws-connector
      image-name: archipelago-workers
      deployment-environment: dev
    secrets: inherit
