name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  archipelago-core-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@test4
    with:
      service-name: archipelago-workers
      env: dev
    secrets: inherit

  archipelago-stats-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@test4
    with:
      service-name: archipelago-stats
      image-name: archipelago-workers
      env: dev
    secrets: inherit

  archipelago-ws-connector-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@test4
    with:
      service-name: archipelago-ws-connector
      image-name: archipelago-workers
      env: dev
    secrets: inherit
