name: Build API Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build-docs:
    uses: decentraland/platform-actions/.github/workflows/apps-docs.yml@fix/docs
    with:
      api-spec-file: docs/openapi.yaml
      api-spec-name: 'archipelago-workers-api'
      node-version: '20'
    secrets: inherit
